[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/stripeWebhook"
  to = "/.netlify/functions/stripeWebhook"
  status = 200